name: Nascraft
version: '${project.version}'
main: me.bounser.nascraft.Nascraft
api-version: 1.13
softdepend: [ Vault, PlaceholderAPI, AdvancedGUI, DiscordSRV ]
authors: [ bounser ]
description: Market valuations in minecraft